
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Layout from "./compontents/home/Layout";
import CommonTransaction from "./api/common";
import AuthSession from "./api/auth/AuthSession";
import ErrorScreen from "./compontents/common/errorScreen/Index";
import LoadingScreen from "./compontents/common/loadingScreen/Index";
import AlertPopup from "./compontents/design/popup/AlertPopup";
import LoadingScreen2 from "./compontents/common/loadingScreen/Index2";
import mainScrollYn from "./store/mainScrollYn";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app", 
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={`${poppins.className}`}>
      <body className={""}>
        <AuthSession>
          <CommonTransaction>
            <LoadingScreen/>
            <LoadingScreen2/>
            <ErrorScreen/>
            <AlertPopup/>
            <div id="portal" />
            <Layout>
            {children}
            </Layout>
          </CommonTransaction>
        </AuthSession>
      </body>
    </html>
  );
}
